<?php

namespace Database\Seeders;

use App\Models\Glossary;
use Illuminate\Database\Seeder;

class GlossarySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $glossaries = [
            [
                'word' => 'Annual appreciation',
                'description' => 'projected growth in the market value of the asset over 1 year.',
                'explanation' => '<p>For example, consider a property that is acquired at a price of AED 1,000,000 with buying costs worth AED 100,000. The total investment amount is AED 1,100,000.</p><p>Assuming the property is sold after a few years at a price of AED 1,500,000 (net of selling costs), the capital appreciation is AED 400,000, or 36.4% (i.e. AED 400,000 / AED 1,100,000).</p>',
                'show' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'word' => 'Annualised return',
                'description' => 'Total ROI over 5 years (rental income/net yield + annual appreciation) however averaged on an annual basis.',
                'explanation' => '<p>Our properties usually have around a 50% total ROI over 5 years, so averaging out over a yearly basis is around 10%.</p>',
                'show' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'word' => 'Dividend',
                'description' => 'The payout an investor in an asset receives after subtracting all costs.',
                'explanation' => '<p>For example, in the case of 10 investors co-owning a property, the dividend is the payment each investor receives. It is the total rent generated by the property divided by 10 (minus all costs).&nbsp;</p>',
                'show' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'word' => 'Gross yield',
                'description' => 'projected annual percentage return that investment generates before deducting all expenses, like management fees and maintenance costs',
                'explanation' => '<p>For example, if a property is priced at AED 1,000,000 and rented for AED 100,000 per year, that property generates a gross income of AED 100,000 and a gross yield of 10%.</p>',
                'show' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'word' => 'Funding target',
                'description' => 'The capital required to be raised in order to complete the purchase of the property.',
                'explanation' => '<p>For example if a fund is looking to purchase a property at a price of AED 1,000,000 and executing the transaction incurs costs of AED 50,000 the funding target will be AED 1,050,000.</p>',
                'show' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'word' => 'ROI (Return on Investment)',
                'description' => 'The ratio of the price differentials of an asset at the end of a period plus all the income generated by an asset to the original price paid for that asset.',
                'explanation' => '<p>For example a property that is purchased for price A and sold after 5 years for price B, the ROI is:</p><p>[B-A+Rental income during the 5 years]/A.</p>',
                'show' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'word' => 'Transaction costs',
                'description' => 'The additional costs incurred during the execution of a deal in addition to the asset purchase price.',
                'explanation' => '<p><i>For example, purchasing investment property in Dubai requires paying transfer fees, registration fees, and some additional charges like valuation and KYC charges.</i></p>',
                'show' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        Glossary::insert($glossaries);
    }
}
